### ISSUE TITLE
operations.xml:12-12: Необходимо добавить сюда признак...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/laweb#59]
The puzzle `55-e8d3de82` in [`lawe/templates/operations.xml`](https://github.com/DronMDF/laweb/blob/master/lawe/templates/operations.xml) (lines 12-12) has to be resolved: Необходимо добавить сюда признак доступности счета

The puzzle was created by Andrey Valyaev on 21-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by DronMDF** [comment]
related to #9

**Comment by 0pdd** [comment]
The puzzle `55-e8d3de82` has disappeared from the source code, that's why I closed this issue.
